from enum import Enum


class Languages(Enum):
    ENG = "ENG"
    FRE = "FRE"
    SWE = "SWE"
    CZE = "CZE"
    TUR = "TUR"
    SPA = "SPA"
    SCR = "SCR"
    RUS = "RUS"
    POR = "POR"
    NOR = "NOR"
    LAV = "LAV"
    KOR = "KOR"
    JPN = "JPN"
    ITA = "ITA"
    HUN = "HUN"
    HEB = "HEB"
    GRE = "GRE"
    GER = "GER"
    FIN = "FIN"
    EST = "EST"
    DUT = "DUT"
    CHI = "CHI"
    BAQ = "BAQ"
